# Generated by Django 4.1.2 on 2023-03-08 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craft', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Crafts',
        ),
    ]
