# Generated by Django 4.1 on 2022-11-21 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_name_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='Категоря'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_es',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='Категоря'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_ja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='Категоря'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='Категоря'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ja',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Название Устройства'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_es',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Название Устройства'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ja',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Название Устройства'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Название Устройства'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_es',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_ja',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Краткое описание'),
        ),
    ]
