# Generated by Django 4.1 on 2022-12-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_category_en_product_category_es_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_es',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_ja',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_zh_hans',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Краткое описание'),
        ),
    ]
